/*
 *  Copyright 2011 Michael R. Elliott <mre@m79.net>.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  under the License.
 */

/*
 * FlagRadioButtonForm.java
 *
 * Created on Jan 9, 2011, 11:18:23 AM
 */

package org.sc205.view;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.util.Observable;
import javax.swing.ImageIcon;
import org.sc205.model.Partnership.Affiliation;

/**
 *
 * @author Michael R. Elliott <mre@m79.net>
 */
public class FlagRadioButtonForm extends javax.swing.JPanel {

    /** Creates new form FlagRadioButtonForm */
    public FlagRadioButtonForm() {
        initComponents();
        BufferedImage euroFlag =
             ImageProvider.instance().get( Affiliation.EUROPEAN, 80, 60 );
        european.setIcon( new ImageIcon( euroFlag ));
        BufferedImage amCanFlag =
             ImageProvider.instance().get( Affiliation.AMERICAN, 80, 60 );
        american.setIcon( new ImageIcon( amCanFlag ));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      buttonGroup1 = new javax.swing.ButtonGroup();
      euroPanel = new javax.swing.JPanel();
      european = new javax.swing.JRadioButton();
      amCanPanel = new javax.swing.JPanel();
      american = new javax.swing.JRadioButton();

      setName("Form"); // NOI18N
      setPreferredSize(new java.awt.Dimension(100, 140));

      euroPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
      euroPanel.setName("euroPanel"); // NOI18N

      buttonGroup1.add(european);
      org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.sc205.ISLS.class).getContext().getResourceMap(FlagRadioButtonForm.class);
      european.setText(resourceMap.getString("european.text")); // NOI18N
      european.setName("european"); // NOI18N
      european.addItemListener(new java.awt.event.ItemListener() {
         public void itemStateChanged(java.awt.event.ItemEvent evt) {
            europeanItemStateChanged(evt);
         }
      });

      javax.swing.GroupLayout euroPanelLayout = new javax.swing.GroupLayout(euroPanel);
      euroPanel.setLayout(euroPanelLayout);
      euroPanelLayout.setHorizontalGroup(
         euroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(euroPanelLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(european)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      euroPanelLayout.setVerticalGroup(
         euroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(euroPanelLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(european)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      amCanPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
      amCanPanel.setName("amCanPanel"); // NOI18N

      buttonGroup1.add(american);
      american.setText(resourceMap.getString("american.text")); // NOI18N
      american.setName("american"); // NOI18N
      american.addItemListener(new java.awt.event.ItemListener() {
         public void itemStateChanged(java.awt.event.ItemEvent evt) {
            americanItemStateChanged(evt);
         }
      });

      javax.swing.GroupLayout amCanPanelLayout = new javax.swing.GroupLayout(amCanPanel);
      amCanPanel.setLayout(amCanPanelLayout);
      amCanPanelLayout.setHorizontalGroup(
         amCanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(amCanPanelLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(american)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      amCanPanelLayout.setVerticalGroup(
         amCanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(amCanPanelLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(american)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(euroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(amCanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(40, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(euroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(20, 20, 20)
            .addComponent(amCanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(108, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents

    private void europeanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_europeanItemStateChanged
       final Color bg = european.isSelected() ? SELECTED : DESELECTED;
       obs.notifyObservers( this );
       euroPanel.setBackground( bg );
    }//GEN-LAST:event_europeanItemStateChanged

    private void americanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_americanItemStateChanged
       final Color bg = american.isSelected() ? SELECTED : DESELECTED;
       obs.notifyObservers( this );
       amCanPanel.setBackground( bg );
    }//GEN-LAST:event_americanItemStateChanged


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel amCanPanel;
   private javax.swing.JRadioButton american;
   private javax.swing.ButtonGroup buttonGroup1;
   private javax.swing.JPanel euroPanel;
   private javax.swing.JRadioButton european;
   // End of variables declaration//GEN-END:variables

   public Affiliation selection() {
      if (american.isSelected())
         return Affiliation.AMERICAN;
      if (european.isSelected())
         return Affiliation.EUROPEAN;
      return null;
   }

   public boolean selectionMade() {
      return european.isSelected() || american.isSelected();
   }

   public Observable getObservable() {
      return obs;
   }

   private Observable obs = new Observable() {

      @Override
      public void notifyObservers( Object o ) {
         setChanged();
         super.notifyObservers( o );
      }
   };

   final private static Color DESELECTED = new Color( 237, 236, 235 );
   final private static Color SELECTED = Color.GRAY;
}
