/*
 *  Copyright 2011 Michael R. Elliott <mre@m79.net>.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *  under the License.
 */

/*
 * EditPartnershipDialog.java
 *
 * Created on Jan 3, 2011, 4:24:51 PM
 */
package org.sc205.controller;

import java.awt.Component;
import org.sc205.model.Partnership;

/**
 *
 * @author Michael R. Elliott <mre@m79.net>
 */
public class EditPartnershipDialog extends javax.swing.JDialog {

   /** Creates new form EditPartnershipDialog */
   public EditPartnershipDialog( java.awt.Frame parent, boolean modal ) {
      super( parent, modal );
      initComponents();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      cancel = new javax.swing.JButton();
      ok = new javax.swing.JButton();
      title = new javax.swing.JLabel();
      names = new javax.swing.JPanel();
      name0 = new javax.swing.JTextField();
      name1 = new javax.swing.JTextField();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setName("Form"); // NOI18N

      org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.sc205.ISLS.class).getContext().getResourceMap(EditPartnershipDialog.class);
      cancel.setText(resourceMap.getString("cancel.text")); // NOI18N
      cancel.setName("cancel"); // NOI18N
      cancel.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cancelActionPerformed(evt);
         }
      });

      ok.setText(resourceMap.getString("ok.text")); // NOI18N
      ok.setName("ok"); // NOI18N
      ok.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            okActionPerformed(evt);
         }
      });

      title.setBackground(resourceMap.getColor("title.background")); // NOI18N
      title.setFont(resourceMap.getFont("title.font")); // NOI18N
      title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      title.setText(resourceMap.getString("title.text")); // NOI18N
      title.setBorder(javax.swing.BorderFactory.createEtchedBorder());
      title.setName("title"); // NOI18N
      title.setOpaque(true);

      names.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("names.border.title"))); // NOI18N
      names.setName("names"); // NOI18N

      name0.setName("name0"); // NOI18N

      name1.setName("name1"); // NOI18N

      javax.swing.GroupLayout namesLayout = new javax.swing.GroupLayout(names);
      names.setLayout(namesLayout);
      namesLayout.setHorizontalGroup(
         namesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(namesLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(namesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(name0, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
               .addComponent(name1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
            .addContainerGap())
      );
      namesLayout.setVerticalGroup(
         namesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(namesLayout.createSequentialGroup()
            .addComponent(name0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(ok)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(cancel))
               .addComponent(names, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(names, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(cancel)
               .addComponent(ok))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
       this.dispose();
}//GEN-LAST:event_cancelActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
       partnership.setCurrentName( 0, name0.getText() );
       partnership.setCurrentName( 1, name1.getText() );
       dispose();
       initiator.repaint();
}//GEN-LAST:event_okActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main( String args[] ) {
      java.awt.EventQueue.invokeLater( new Runnable() {

         public void run() {
            EditPartnershipDialog dialog = new EditPartnershipDialog( new javax.swing.JFrame(), true );
            dialog.addWindowListener( new java.awt.event.WindowAdapter() {

               public void windowClosing( java.awt.event.WindowEvent e ) {
                  System.exit( 0 );
               }
            } );
            dialog.setVisible( true );
         }
      } );
   }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton cancel;
   private javax.swing.JTextField name0;
   private javax.swing.JTextField name1;
   private javax.swing.JPanel names;
   private javax.swing.JButton ok;
   private javax.swing.JLabel title;
   // End of variables declaration//GEN-END:variables

   public void setPartnership( Partnership partnership ) {
      this.partnership = partnership;
      name0.setText( partnership.nameAsEntered( 0 ) );
      name1.setText( partnership.nameAsEntered( 1 ) );
   }

   private Component initiator;

   public void setInitiator( Component initiator ) {
      this.initiator = initiator;
   }
   private Partnership partnership;
}
